/**
 * Created by Waldo J. Saccaco (w.saccaco@gmail.com) on 01/03/2017.
 */
export class UserServices{

  users = [{
    "id": 1,
    "first_name": "Evelyn",
    "last_name": "Harper",
    "email": "eharper0@google.com.au",
    "gender": "Female",
    "status": false
  }, {
    "id": 2,
    "first_name": "Willie",
    "last_name": "Lane",
    "email": "wlane1@comcast.net",
    "gender": "Male",
    "status": false
  }, {
    "id": 3,
    "first_name": "Brenda",
    "last_name": "Nichols",
    "email": "bnichols2@imgur.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 4,
    "first_name": "Marie",
    "last_name": "Elliott",
    "email": "melliott3@engadget.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 5,
    "first_name": "Douglas",
    "last_name": "Crawford",
    "email": "dcrawford4@bigcartel.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 6,
    "first_name": "Ashley",
    "last_name": "Moreno",
    "email": "amoreno5@cnn.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 7,
    "first_name": "Robert",
    "last_name": "Moreno",
    "email": "rmoreno6@theguardian.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 8,
    "first_name": "Amy",
    "last_name": "Carr",
    "email": "acarr7@cnn.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 9,
    "first_name": "Phillip",
    "last_name": "Owens",
    "email": "powens8@squarespace.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 10,
    "first_name": "Robin",
    "last_name": "Gutierrez",
    "email": "rgutierrez9@xing.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 11,
    "first_name": "Melissa",
    "last_name": "Berry",
    "email": "mberrya@shutterfly.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 12,
    "first_name": "Donald",
    "last_name": "Mendoza",
    "email": "dmendozab@live.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 13,
    "first_name": "Andrew",
    "last_name": "Morrison",
    "email": "amorrisonc@usnews.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 14,
    "first_name": "Patricia",
    "last_name": "Hanson",
    "email": "phansond@histats.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 15,
    "first_name": "Frances",
    "last_name": "Hamilton",
    "email": "fhamiltone@blogs.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 16,
    "first_name": "Bonnie",
    "last_name": "Gilbert",
    "email": "bgilbertf@prweb.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 17,
    "first_name": "Cheryl",
    "last_name": "Banks",
    "email": "cbanksg@ft.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 18,
    "first_name": "Raymond",
    "last_name": "Sanchez",
    "email": "rsanchezh@360.cn",
    "gender": "Male",
    "status": true
  }, {
    "id": 19,
    "first_name": "Joshua",
    "last_name": "Davis",
    "email": "jdavisi@meetup.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 20,
    "first_name": "Antonio",
    "last_name": "Foster",
    "email": "afosterj@hao123.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 21,
    "first_name": "Louise",
    "last_name": "Robertson",
    "email": "lrobertsonk@ezinearticles.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 22,
    "first_name": "Jennifer",
    "last_name": "Stone",
    "email": "jstonel@mtv.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 23,
    "first_name": "Terry",
    "last_name": "Rodriguez",
    "email": "trodriguezm@auda.org.au",
    "gender": "Male",
    "status": true
  }, {
    "id": 24,
    "first_name": "Lois",
    "last_name": "Robertson",
    "email": "lrobertsonn@digg.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 25,
    "first_name": "Ronald",
    "last_name": "Bennett",
    "email": "rbennetto@state.gov",
    "gender": "Male",
    "status": false
  }, {
    "id": 26,
    "first_name": "Joyce",
    "last_name": "Walker",
    "email": "jwalkerp@topsy.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 27,
    "first_name": "Carolyn",
    "last_name": "Lopez",
    "email": "clopezq@newsvine.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 28,
    "first_name": "Wayne",
    "last_name": "Murray",
    "email": "wmurrayr@youtu.be",
    "gender": "Male",
    "status": true
  }, {
    "id": 29,
    "first_name": "Mary",
    "last_name": "Arnold",
    "email": "marnolds@wp.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 30,
    "first_name": "Betty",
    "last_name": "Ferguson",
    "email": "bfergusont@weebly.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 31,
    "first_name": "Frank",
    "last_name": "Peterson",
    "email": "fpetersonu@biglobe.ne.jp",
    "gender": "Male",
    "status": true
  }, {
    "id": 32,
    "first_name": "Carlos",
    "last_name": "Wagner",
    "email": "cwagnerv@shinystat.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 33,
    "first_name": "Thomas",
    "last_name": "Fisher",
    "email": "tfisherw@mtv.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 34,
    "first_name": "David",
    "last_name": "Butler",
    "email": "dbutlerx@usgs.gov",
    "gender": "Male",
    "status": false
  }, {
    "id": 35,
    "first_name": "Karen",
    "last_name": "Robertson",
    "email": "krobertsony@baidu.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 36,
    "first_name": "Sara",
    "last_name": "Ramirez",
    "email": "sramirezz@paypal.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 37,
    "first_name": "Joyce",
    "last_name": "Hunter",
    "email": "jhunter10@lulu.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 38,
    "first_name": "Arthur",
    "last_name": "Mccoy",
    "email": "amccoy11@newsvine.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 39,
    "first_name": "Randy",
    "last_name": "Fowler",
    "email": "rfowler12@xrea.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 40,
    "first_name": "Kimberly",
    "last_name": "Bryant",
    "email": "kbryant13@java.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 41,
    "first_name": "Scott",
    "last_name": "Weaver",
    "email": "sweaver14@netlog.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 42,
    "first_name": "Margaret",
    "last_name": "Hicks",
    "email": "mhicks15@freewebs.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 43,
    "first_name": "Larry",
    "last_name": "Roberts",
    "email": "lroberts16@amazonaws.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 44,
    "first_name": "Joe",
    "last_name": "Kennedy",
    "email": "jkennedy17@berkeley.edu",
    "gender": "Male",
    "status": false
  }, {
    "id": 45,
    "first_name": "Robert",
    "last_name": "Olson",
    "email": "rolson18@creativecommons.org",
    "gender": "Male",
    "status": false
  }, {
    "id": 46,
    "first_name": "Carolyn",
    "last_name": "Hall",
    "email": "chall19@washington.edu",
    "gender": "Female",
    "status": false
  }, {
    "id": 47,
    "first_name": "Robin",
    "last_name": "Dixon",
    "email": "rdixon1a@biglobe.ne.jp",
    "gender": "Female",
    "status": false
  }, {
    "id": 48,
    "first_name": "Beverly",
    "last_name": "Knight",
    "email": "bknight1b@google.com.au",
    "gender": "Female",
    "status": true
  }, {
    "id": 49,
    "first_name": "Wayne",
    "last_name": "Henderson",
    "email": "whenderson1c@vimeo.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 50,
    "first_name": "Helen",
    "last_name": "Gibson",
    "email": "hgibson1d@usnews.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 51,
    "first_name": "Pamela",
    "last_name": "Hernandez",
    "email": "phernandez1e@chronoengine.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 52,
    "first_name": "Beverly",
    "last_name": "Tucker",
    "email": "btucker1f@patch.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 53,
    "first_name": "Sara",
    "last_name": "Castillo",
    "email": "scastillo1g@godaddy.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 54,
    "first_name": "Anne",
    "last_name": "Boyd",
    "email": "aboyd1h@studiopress.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 55,
    "first_name": "Julia",
    "last_name": "Pierce",
    "email": "jpierce1i@nasa.gov",
    "gender": "Female",
    "status": false
  }, {
    "id": 56,
    "first_name": "Jeffrey",
    "last_name": "Elliott",
    "email": "jelliott1j@google.ca",
    "gender": "Male",
    "status": true
  }, {
    "id": 57,
    "first_name": "Kathleen",
    "last_name": "Hudson",
    "email": "khudson1k@examiner.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 58,
    "first_name": "Jessica",
    "last_name": "Alvarez",
    "email": "jalvarez1l@unc.edu",
    "gender": "Female",
    "status": true
  }, {
    "id": 59,
    "first_name": "Anne",
    "last_name": "Fisher",
    "email": "afisher1m@cisco.com",
    "gender": "Female",
    "status": true
  }, {
    "id": 60,
    "first_name": "Ernest",
    "last_name": "Lawson",
    "email": "elawson1n@webnode.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 61,
    "first_name": "Lori",
    "last_name": "Gibson",
    "email": "lgibson1o@ox.ac.uk",
    "gender": "Female",
    "status": true
  }, {
    "id": 62,
    "first_name": "Timothy",
    "last_name": "Fox",
    "email": "tfox1p@slate.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 63,
    "first_name": "Thomas",
    "last_name": "Austin",
    "email": "taustin1q@imgur.com",
    "gender": "Male",
    "status": false
  }, {
    "id": 64,
    "first_name": "Louis",
    "last_name": "Johnston",
    "email": "ljohnston1r@addtoany.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 65,
    "first_name": "Anne",
    "last_name": "Anderson",
    "email": "aanderson1s@wired.com",
    "gender": "Female",
    "status": false
  }, {
    "id": 66,
    "first_name": "Russell",
    "last_name": "Allen",
    "email": "rallen1t@telegraph.co.uk",
    "gender": "Male",
    "status": false
  }, {
    "id": 67,
    "first_name": "Nicholas",
    "last_name": "Brown",
    "email": "nbrown1u@twitter.com",
    "gender": "Male",
    "status": true
  }, {
    "id": 68,
    "first_name": "James",
    "last_name": "Gonzales",
    "email": "jgonzales1v@sourceforge.net",
    "gender": "Male",
    "status": true
  }];

  listUsers(){
    return this.users;
  }

  find(id){
    return this.users.find(( user ) => user.id == id);
  }

}
